In [1]:
import pandas as pd
import db_mgmt as mgmt
import os
import sqlite3

In [2]:
output_dir = 'outputs/CANOE_20260411_10_56/'
db_file = 'canoe_hr_16d.sqlite'
data = mgmt.sqlite_to_dfs(output_dir + db_file)

In [6]:
bc = data['OutputBuiltCapacity'].copy()
bc = bc.loc[bc['sector']=='transportation']

In [7]:
bc

     scenario region          sector               tech  vintage   capacity
0        zulu     QC  transportation      T_HDV_AJP_JFL     2030  21.898558
3        zulu     MB  transportation      T_HDV_BIC_DSL     2030   0.013219
4        zulu     MB  transportation   T_LDV_LTP_BEV200     2045   0.000384
6        zulu     NB  transportation       T_HDV_RF_DSL     2040   0.000036
7        zulu     QC  transportation   T_MDV_T_DSL_PHEV     2045   0.000011
...       ...    ...             ...                ...      ...        ...
5771     zulu     BC  transportation        T_LDV_M_BEV     2040   0.000204
5773     zulu     NS  transportation       T_HDV_BT_BEV     2035   0.001292
5774     zulu     ON  transportation  T_LDV_LTP_FCEV400     2025   0.000047
5775     zulu  NLLAB  transportation    T_LDV_C_FCEV400     2035   0.000063
5778     zulu     ON  transportation   T_LDV_LTF_BEV300     2025   0.000104

[3123 rows x 6 columns]

     scenario region          sector               tech  vintage   capacity
0        zulu     QC  transportation      T_HDV_AJP_JFL     2030  21.898558
3        zulu     MB  transportation      T_HDV_BIC_DSL     2030   0.013219
4        zulu     MB  transportation   T_LDV_LTP_BEV200     2045   0.000384
6        zulu     NB  transportation       T_HDV_RF_DSL     2040   0.000036
7        zulu     QC  transportation   T_MDV_T_DSL_PHEV     2045   0.000011
...       ...    ...             ...                ...      ...        ...
5771     zulu     BC  transportation        T_LDV_M_BEV     2040   0.000204
5773     zulu     NS  transportation       T_HDV_BT_BEV     2035   0.001292
5774     zulu     ON  transportation  T_LDV_LTP_FCEV400     2025   0.000047
5775     zulu  NLLAB  transportation    T_LDV_C_FCEV400     2035   0.000063
5778     zulu     ON  transportation   T_LDV_LTF_BEV300     2025   0.000104

[3123 rows x 6 columns]